### PR TITLE
Moved docker to alpine. 

### PR DESCRIPTION
**Pull request by dseguy**
So, here is the docker-exakat version for Codacy.

It is based on alpine version, as Rafael did. 
In the process, I managed to removed one of the side build (the gremlin-plugin). 

I have tested it locally successfully, but not with circleCI.  The running command is in the build.sh file.

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@dseguy Nice work. Now since you removed build.Dockerfile you need to remove lines 18 and 19 from https://github.com/dseguy/exakat-docker/blob/codacy/circle.yml#L18 and it should run.

**Comment by dseguy** [comment]
So, I just amended the PR with your suggestion.

I think the final image is still too big. I may need help to reduce this size. 
I have the feel that I'm running too much software while building the image.

**Comment by rtfpessoa** [comment]
@dseguy seems like it is building but the dockers are not finishing.

**Comment by dseguy** [comment]
I read that in the CI report. 
I ran it successfully here, on a real project and on the 4 tests that are in the docker. 

Let me see if I can run the codacy test suite.

**Comment by dseguy** [comment]
I couldn't run codacy-plugin-test : 

 sbt "run-main codacy.plugins.DockerTest plugin exakat/codacy:latest" -Djava.io.tmpdir=$HOME/tmp
[warn] No sbt.version set in project/build.properties, base directory: /Users/famille/Desktop/docker-Codacy/docs/tests
[info] Set current project to tests (in build file:/Users/famille/Desktop/docker-Codacy/docs/tests/)
[error] Expected ID character
[error] Not a valid command: run-main
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: run-main (similar: runMain, bgRunMain, run)
[error] run-main codacy.plugins.DockerTest plugin exakat/codacy:latest
[error]         ^

**Comment by dseguy** [comment]
Also, the circleCI test mention other errors : Could that be important ? 

[info] Running codacy.plugins.DockerTest pattern codacy-exakat:latest
Error response from daemon: lstat /var/lib/docker/btrfs/subvolumes/db7468d09e7c3b45420ccea422369b17925da5e3c303e84fa6ba748ba0ad6806/docs/directory-tests: no such file or directory
Error response from daemon: Driver btrfs failed to remove root filesystem db7468d09e7c3b45420ccea422369b17925da5e3c303e84fa6ba748ba0ad6806: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for db7468d09e7c3b45420ccea422369b17925da5e3c303e84fa6ba748ba0ad6806: operation not permitted
Error: failed to remove containers: [db7468d09e7c3b45420ccea422369b17925da5e3c303e84fa6ba748ba0ad6806]

**Comment by rtfpessoa** [comment]
Those errors as mostly due to circle ci limitations but are not a problem.

Your command failed because you are not in the directory of the test project.
Follow the steps bellow to do it:
```sh
git clone https://github.com/codacy/codacy-plugins-test
cd codacy-plugins-test
sbt -Dcodacy.tests.noremove=true "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest [optional-test-file-name]"
```

This will also allow you to see the dockers that were executed and look at their logs.
Let mw know it it worked.

**Comment by dseguy** [comment]
OK, now it worked as expected with the codacy-test-plugin. I went up to the 'freeze' moment, that CircleCI reported. 

Can you tell me how is the test run ?  I'm using this command : 

docker run -v $(pwd)/docs/tests:/src --user docker exakat/codacy:latest

with a .codacy.json file added in the docs/tests folder, with all patterns and all files. 
I guess for Unit Test, the .codacy.json only has 1 file and the corresponding pattern.
Is it another way ?

**Comment by rtfpessoa** [comment]
@dseguy we add some security params to map our prod setup.
`docker --net=none --privileged=false --user=docker`, still in prod we might add some more but this should be a start.

**Comment by dseguy** [comment]
Let me try that, just to be sure.

**Comment by dseguy** [comment]
it works like a charm with  --net=none --privileged=false  .

Can you tell me how the tests are run ? 
Adding a .codacy.json file to the docs/tests folder, and processing one by one all the files ?

**Comment by dseguy** [comment]
I think I found something  --drop-cap=ALL leads to a quick halt, an error and not results.
Though, it doesn't hang for long. 

I'm searching with the codacy-test-plugin.

**Comment by rtfpessoa** [comment]
The tests generate a `.codacy.json` file with the patterns they are running and the files. In this case should be one pattern and one file each time only.

**Comment by rtfpessoa** [comment]
This is the base command we use https://github.com/codacy/codacy-plugins-test/blob/2e313156f17d9b74e6daf55c4f2dd84288a453eb/src/main/scala/codacy/plugins/test/DockerHelpers.scala#L16 but in prod we add `--drop-cap=ALL`.

**Comment by dseguy** [comment]
I checked them with the options :  "--net=none", "--privileged=false", "--user=docker" and also dropcap : it works well with all of them. Results are provided as expected.

The fun part is : 
```
sbt -Dcodacy.tests.noremove=true "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest [optional-test-file-name]"
reports :  Running PatternsTests: 
 [Success] PatternTests$ 
 [Success] All tests passed! 
[success] Total time: 2 s, completed Mar 18, 2018 6:23:31 PM

```
Now, 2 seconds of execution time is not credible. This is wrong.


Each of the separate tests reports that nothing was reported : 
 ```
sbt -Dcodacy.tests.noremove=true "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest  Functions_AliasesUsage"


 Running PatternsTests: 

- Functions_AliasesUsage.php should have 2 matches with patterns: Functions/AliasesUsage 
 No results received! 
   + 0 matches found in lines:  
   -> Found:
   
  -> Expected:
   (Functions/AliasesUsage,7,Warning)
   (Functions/AliasesUsage,9,Warning)
  --------------------------------------
  -> Missing:
   (Functions/AliasesUsage,7,Warning)
   (Functions/AliasesUsage,9,Warning)
  -> Extra:
    
 [Failure] PatternTests$ 
 [Failure] Some tests failed! 
```

Also, this command doesn't provides anything is 'docker ps' : no running container.

`docker run  -v $(pwd)/docs/tests:/src --user docker exakat/codacy:latest`
with a manual .codacy.json and test file in $(pwd)/docs/tests provides the expected results. 
 
What can I check now ?

**Comment by rtfpessoa** [comment]
@dseguy the dockers will have exited. You need to do `docker ps -a` and then `docker logs <name>`

**Comment by dseguy** [comment]
When run from codacy-plugin-test, Exakat complains there are no files available to process.

When testing manually, I use this .codacy.json : 
```
{
    "files": [
        "Functions/AliasesUsage"
    ],
    "tools": [
        {
            "name": "exakat",
            "patterns": [
                "Functions/AliasesUsage"
            ]
        }
    ]
}
```
So, the file for test is actually the same as the patternId.

What am I missing ?

**Comment by dseguy** [comment]
I added ls /src ; more /src/.codacy.json (listing /src folder, and reading the .codacy.json file in /src )
and both are not available when running sbt. 

According to https://support.codacy.com/hc/en-us/articles/207994725-Tool-Developer-Guide, that's where they are stored.

**Comment by rtfpessoa** [comment]
Hmm that is weird.

I did a test locally with `.codacy.json` inside `$(pwd)/docs/tests`:
```
{
    "files": [
        "Functions_AliasesUsage.php"
    ],
    "tools": [
        {
            "name": "exakat",
            "patterns": [
                "Functions/AliasesUsage"
            ]
        }
    ]
}
```

and command:
`docker run -v $(pwd)/docs/tests:/src --user docker exakat/codacy:latest`

and got an error from exakat:

```
Error : One of the options -P <One/rule>|-T <"Thema"> is required. None provided.

on file phar:///usr/src/exakat/exakat.phar/library/Exakat/Tasks/Analyze.php
on line 90
```

Can you try?

**Comment by dseguy** [comment]
I fixed that in the upcoming version 1.1.9 (you have 1.1.8). The new version is planned for later today. 

I'm trying to check the rest of the UT before release.

**Comment by rtfpessoa** [comment]
Then can you run with my config and files to see what you get?

I am also thinking that the test project can have some issues with the
pattern names having slashes (/)

**Comment by dseguy** [comment]
Problems with the / would make sense. 

I think sbt makes a file copy, but ends up having a directory to copy. 

I tried various combinaisons of .codacy.json : with or without .php, with _ or / in the file name. As long as the test file exists (with _ or / ) and the patternId is correct, it works fine. 

do you have a way to make codacy-plugin-test handle the / ? That would be the best, I think.
I can't change the patternId, but I can handle any test-filename, if that helps.

**Comment by rtfpessoa** [comment]
After you release the new version I will be able to debug it locally and can take a look. Let me know when I can test.

**Comment by dseguy** [comment]
Version 1.1.9 is published. Just change the version number for Exakat, and you are good to go. 
Keep me posted.

**Comment by rtfpessoa** [comment]
@dseguy after some tests I think I got it working manually.
Still during the automated tests it seems to fail, but I noticed that the output seems to have some issues:
* `patternid` should be `patternId`
* file starts with `\/` and it should be clean. e.g. `\/file.php` should be `file.php`

Can you make a test version with this fixed?

**Comment by dseguy** [comment]
Sure thing.

**Comment by dseguy** [comment]
Here is a sample report from the 1.1.9a version, being uploaded (wait for 5 min) : 

{"filename":"library\/Exakat\/Tasks\/Load.php","message":"PHP 7.3 Last Empty Argument","patternId":"Php\/PHP73LastEmptyArgument","line":3969}

I should have spotted that with the codacy-plugin-test, I guess.

**Comment by rtfpessoa** [comment]
@dseguy I do not think it is your fault. We should give you better messages.

We are now working on some improvements to the tools and eventually we will be able to improve this too.

Let me know when it is ready.

**Comment by dseguy** [comment]
the 1.1.9a is online now.  Use this version in the dockerfile, it should be fine. 

Keep me posted when I can pull the new codacy-plugin-test repo and test it too.

**Comment by rtfpessoa** [comment]
Seems like something is weird with this version. I am getting an HTML when I run it. Any ideas?

**Comment by dseguy** [comment]
Try again now, that was a glitch in the publication system.

**Comment by rtfpessoa** [comment]
I think I found a couple more issues while debugging:
* The file field in the output should be `file` and not `filename`
* The json from the config that is passed to exakat will be:
```
{
    "files":[
        "Functions_AliasesUsage.php"
    ],
    "tools": [
        {
            "name": "exakat",
            "patterns": [
                { 
                    "patternId": "Functions/AliasesUsage"
                 }
             ]
         }
    ]
}
```
 
and not

```
{
    "files": [
        "Functions_AliasesUsage.php"
    ],
    "tools": [
        {
            "name": "exakat",
            "patterns": [
                "Functions/AliasesUsage"
            ]
        }
    ]
}
```

I think this should be the final problems. Can you take a look?

**Comment by dseguy** [comment]
OK, that won't be long.

**Comment by dseguy** [comment]
New version 1.1.9b is up.
it replace 1.1.9a

**Comment by rtfpessoa** [comment]
Seems like I am getting the issue:
```
Error : One of the options -P <One/rule>|-T <"Thema"> is required. None provided.

on file phar:///usr/src/exakat/exakat.phar/library/Exakat/Tasks/Analyze.php
on line 90
```

Any ideas?

**Comment by rtfpessoa** [comment]
Ups my bad. Seems like it is working.

**Comment by rtfpessoa** [comment]
Seems like if you update the version in this PR to `1.1.9b` the tests should pass. Can you do it?

**Comment by rtfpessoa** [comment]
Nice work @dseguy 👍

**Comment by rtfpessoa** [comment]
Seems like I was able to do the update in the UI.

**Comment by dseguy** [comment]
Good news :) 

Can I pull the codacy-plugin-test and check that here too ?

**Comment by rtfpessoa** [comment]
Seems like circleci is having problems to run.

**Comment by rtfpessoa** [comment]
You can use the plugins test locally and it will run. But seems like might be a resource problem.

**Comment by dseguy** [comment]
resource problem ? what kind of resources ?

**Comment by dseguy** [comment]
Also, I think the final image is quite large. Any suggestions to reduce this ? 

I think I followed the same path than Rafael, but even the base is 525Mb. 
And the dependencies are way lesser than for exakat 1.0.0 - 

If you have any advice, I'll look into it.

**Comment by rtfpessoa** [comment]
Regarding the resouces, I was refering to CPU or RAM. Since it ran in my pc in the same conditions.
Regarding the image size I would have to check and maybe talk with @mrfyda.

But usually you should install only what you need, and make the builds of things separately.
But the size can be dealt with later.

Now would be important to understand why it is taking too long on CircleCI.

**Comment by dseguy** [comment]
I tried to run the tests with the 1.1.9b version, and the dockerfile : 

`sbt "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest"`

I get ' No results received!' for every 4 UT available. 
Is there something I have to update to make it run ? codacy-plugin-test may be ? (Last commit is december 20, 2017).

**Comment by dseguy** [comment]
I added 'curl-dev to the 'apk add' installation command, as a bug is reported with curl on alpine.

**Comment by rtfpessoa** [comment]
I did:

```sh
./build.sh
sbt "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest"
```

and I got:

```
[info] Loading global plugins from /Users/rtfpessoa/.sbt/0.13/plugins
[info] Updating {file:/Users/rtfpessoa/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/rtfpessoa/qamine/codacy-plugins-test/project
[info] Updating {file:/Users/rtfpessoa/qamine/codacy-plugins-test/project/}codacy-plugins-test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to codacy-plugins-test (in build file:/Users/rtfpessoa/qamine/codacy-plugins-test/)
[info] Running codacy.plugins.DockerTest pattern exakat/codacy:latest
Error response from daemon: Could not find the file /docs/directory-tests in container b38b52e789f712a480d7119b834e838f76bab4fec03acea6ff6946a772a40131
 Running PatternsTests:
 - Functions_AliasesUsage.php should have 2 matches with patterns: Functions/AliasesUsage
 2 results received.
   + 2 matches found in lines: 7, 9
   Results found matched the expected:
   (Functions/AliasesUsage,7,Warning)
   (Functions/AliasesUsage,9,Warning)
 - Structures_OrDie.php should have 3 matches with patterns: Structures/OrDie
 3 results received.
   + 3 matches found in lines: 5, 8, 11
   Results found matched the expected:
   (Structures/OrDie,5,Warning)
   (Structures/OrDie,8,Warning)
   (Structures/OrDie,11,Warning)
 - Functions_WrongOptionalParameter.php should have 9 matches with patterns: Functions/WrongOptionalParameter
 9 results received.
   + 9 matches found in lines: 13, 15, 17, 20, 22, 24, 26, 28, 30
   Results found matched the expected:
   (Functions/WrongOptionalParameter,13,Warning)
   (Functions/WrongOptionalParameter,15,Warning)
   (Functions/WrongOptionalParameter,17,Warning)
   (Functions/WrongOptionalParameter,20,Warning)
   (Functions/WrongOptionalParameter,22,Warning)
   (Functions/WrongOptionalParameter,24,Warning)
   (Functions/WrongOptionalParameter,26,Warning)
   (Functions/WrongOptionalParameter,28,Warning)
   (Functions/WrongOptionalParameter,30,Warning)
 - Functions_TooManyLocalVariables.php should have 3 matches with patterns: Functions/TooManyLocalVariables
 3 results received.
   + 3 matches found in lines: 5, 95, 142
   Results found matched the expected:
   (Functions/TooManyLocalVariables,5,Warning)
   (Functions/TooManyLocalVariables,95,Warning)
   (Functions/TooManyLocalVariables,142,Warning)
 [Success] PatternTests$
 [Success] All tests passed!
[success] Total time: 228 s, completed 22-Mar-2018 14:08:49
```

**Comment by rtfpessoa** [comment]
Seems like only a problem in CircleCi due to the time it takes.

**Comment by dseguy** [comment]
So, at that point, what is the next step ? 

I'll update codacy-plugin-test until I can get the tests to pass (not yet running here) 

`[success] Total time: 228 s, completed 22-Mar-2018 14:08:49` 
This looks what I expect at that point, and it is less than 10 mins in circleCI.

**Comment by rtfpessoa** [comment]
If everything runs on CircleCI we should be able to integrate it in the product. We have a couple of tools in the pipeline and we should be able to put one more.

I just submitted a change to see if single thread will help.

**Comment by dseguy** [comment]
It seems this worked... 👍   Thanks for your help, Rodrigo! 

I guess I can't help for the review.

**Comment by dseguy** [comment]
Some final and non-blocking thoughts : 

- I still can't run the tests with sbt here. codacy-plugin-test is uptodate, but exakat can't find anything to process. "No results received!"
- I've dabbled with base.dockerfile, and I can shave 200Mb by buidling gremlin there. I'll prepare that for the next PR.
- did "-Dcodacy.tests.threads=8" meant that exakat was started 8 times ? If so, this won't work.
- alpine is radically slower than phpcli-7.2. I need to find why/where.

**Comment by rtfpessoa** [comment]
@dseguy,

* Regarding your local tests seems very weird that it does not work. Can you try `sbt -Dcodacy.tests.noremove=true "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest"` and then check `docker ps -a` and then `docker logs <docker-name>` for the exited dockers?
* Regarding the size ideally you should (@mrfyda will also take a look when he gets some time):
    * Remove any downloaded files
    * Do the download and remove in the same step using multi instruction commands to avoid creating docker layers
    * Build anything that is needed in a separate docker and copy the build artifacts to the new one only
* Exactly we would launch 8 dockers one for each of the files. Why is that a problem?
* Ok that is a problem. We can change the base if you think it is faster. We just use alpine because it is slim but ubuntu has made great progress sliming too.

**Comment by dseguy** [comment]
For the 1rst point, I get : 
```
Searching for files

Error : Not a file to process in codacy. The provided file is empty or doesn't compile. 
on file phar:///usr/src/exakat/exakat.phar/library/Exakat/Tasks/Files.php
on line 83
```
Are there recent changes in codacy-plugin-test (the last is the sbt update) ? Exakat can't find anything in the /src folder for the tests.

**Comment by rtfpessoa** [comment]
Can you remove the docker run you have in build.sh? The configuration file in the build.sh is not correct.

Just do in codacy-exakat:
```sh
docker build --no-cache -f base.dockerfile -t exakat/base .
docker build --no-cache -t exakat/codacy .
```
change to the codacy-plugins-test folder:
```sh
sbt "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest"
```

**Comment by dseguy** [comment]
I used a build container to prepare the gremlin database and remove some useless files : The image is down from 959Mb to 639Mb. 

I upgraded exakat to 1.2.0, though it should not have any impact on this current build. We'll keep testing on 1.1.9.

I found a major problem with the alpine container, and I don't understand how you don't experience it yourself : There is no way to start gremlin-server when using the alpine, though it works well on the Ubuntu (phpcli-7.1). When cleaning the database, exakat needs to restart it from within PHP. It uses this command : 

`php -r "exec('cd tinkergraph; rm -rf db/neo4j; /bin/bash ./bin/gremlin-server.sh conf/gsneo4j.yaml >> /dev/null 2>&1 & echo $! & ');"`

Apparently, on alpine, something prevents exec from finishing (the server is actually started), and php hangs eternally. That explains the 10mins we found on CircleCI. This doesn't happens on Ubuntu.

I'm testing another way for the Codacy container : no restart from exakat, but from the initial entrypoint.

**Comment by dseguy** [comment]
Current situation : 

- even with your kind advice, sbt is still reporting that everything is missing. From my tests, it is trying to run the tests with no code, and a folder called .codacy.json. 
- Size : I separated the build for gremlin-server and size is down to 739Mb. 
- 8 dockers : right, that shouldn't be a problem.
- Alpine : the last build of exakat for alpine avoid restarting gremlin server, and that keep performances good.

**Comment by rtfpessoa** [comment]
Regarding `.codacy.json` it should be a file that `codacy-plugins-test` creates.

Can you make sure that inside `docs/tests/**` there is no `.codacy.json` in any directory or subdirectory before you build the docker?

**Comment by dseguy** [comment]
Good idea, that is probably the case. Let me rebuild everything.

**Comment by dseguy** [comment]
There was a .codacy.json in the tests, but removing it didn't help. 
when I add a command 'more /src/.codacy.json' in the entrypoint of the container for debug, and I get : 
'more: read error: Is a directory'.  

There is also this mention : 
`Error response from daemon: Could not find the file /docs/directory-tests in container 67db4d70a8463afb14686130d89c68a8502a0a4576d8a5d0821f81ad061e7263`

**Comment by dseguy** [comment]
Following yesterday checks, I checked everything and committed with the latest Exakat version (1.2.0a).

Image size is down to 653Mb. 
Tests passes manually : 
`docker run  -v $(pwd)/test:/src --user docker exakat/codacy:latest ` (with a .codacy.json generated file).

Automated tests with codacy-plugin-test fail, as previously.
`sbt "run-main codacy.plugins.DockerTest pattern exakat/codacy:latest"`

I updated circleci.yml file, so this may require some fixing.

**Comment by rtfpessoa** [comment]
Currently the build is failing due to https://github.com/codacy/codacy-exakat/pull/4/commits/4c4ca90c5e273c35539e340fde45d671d141f1da#diff-dd735fe866e330560fa772176cb132d2R8 not existing. There must be some path problems somewhere.

**Comment by dseguy** [comment]
The tinkergraph folder is created with the 
`docker run --rm -it -v $(pwd):/mnt exakat/gremlin:latest` command.

did the exakat/gremlin image was correctly built ?

**Comment by rtfpessoa** [comment]
Check the logs on CircleCI I found it there.

**Comment by rtfpessoa** [comment]
I Think I got this. Just committed the update. Lets see if it builds.

**Comment by dseguy** [comment]
Circle CI runs into the same problems than here, though it doesn't take 10 mins to fail. 

I checked the UT with all the options : 
`docker run -it --rm=true --cap-drop=ALL --net=none --privileged=false -v $(pwd)/docs/tests:/src --user docker exakat/codacy:latest`

I reviewed the build log : all was spot on (besides the constant warning about 
`Error removing intermediate container 7a6295f5a337: nosuchcontainer: no such id: 7a6295f5a337890c2c9fe2324965aa581435411b4379e853d156fd848d380b53`

circle.yml  mentions that some cache directories are missing : could it be important ?

**Comment by dseguy** [comment]
With the debugging option for codacy-plugin-test, I reached the feedback from the docker run.
Exakat complains that no code is available for analysis.

I added a 'find / | grep php' to the entrypoint.sh and I could find the tests scripts in the /docs/tests/ folder. Shall I load them from this folder ? 

Or may be in '/docs/directory-tests' ? sbt complains it is missing. 
```
Error response from daemon: Could not find the file /docs/directory-tests in container cb9c8a3d629931559451c9a1c6bc86d3441ebb6ac2fd91af04284ae2390475f8
```

```
/etc/php7
find: ‘/root’: Permission denied
find: ‘/var/cache/ldconfig’: Permission denied
find: ‘/proc/tty/driver’: Permission denied
/etc/php7/php.ini
/etc/php7/conf.d
/etc/php7/conf.d/00_sqlite3.ini
/etc/php7/conf.d/00_json.ini
/etc/php7/conf.d/00_curl.ini
/etc/php7/conf.d/01_phar.ini
/etc/php7/conf.d/00_mbstring.ini
/etc/php7/conf.d/00_tokenizer.ini
/docs/tests/Functions_WrongOptionalParameter.php
/docs/tests/Functions_AliasesUsage.php
/docs/tests/Structures_OrDie.php
/docs/tests/Functions_TooManyLocalVariables.php
/usr/bin/php7
/usr/bin/php
/usr/lib/php7
/usr/lib/php7/modules
/usr/lib/php7/modules/sqlite3.so
/usr/lib/php7/modules/curl.so
/usr/lib/php7/modules/json.so
/usr/lib/php7/modules/phar.so
/usr/lib/php7/modules/tokenizer.so
/usr/lib/php7/modules/mbstring.so

Error : Not a file to process in codacy. The provided file is empty or doesn't compile. 
on file phar:///usr/src/exakat/exakat.phar/library/Exakat/Tasks/Files.php
on line 83

```

**Comment by rtfpessoa** [comment]
The message `Error response from daemon: Could not find the file /docs/directory-tests in container cb9c8a3d629931559451c9a1c6bc86d3441ebb6ac2fd91af04284ae2390475f8` does not matter. It is not an error. Should not even be logged. Is just for debug. Is just the test plugin looking for files in that directory but this plugin does not have tests of that kind.

You need to check your changes since this was running before. Something changed in the meanwhile that broke this.
The plugin mounts the source files in `/src` when it runs the dockers and also places a `/src/.codacy.json` file in there with the configuration.

**Comment by dseguy** [comment]
Dockerfile had a ln -s to the /src folder, and that was a bad idea. 
I moved it to the entrypoint, and it is much better now.

At that point, /src and /src/.codacy.json do exists.
But I get not a single PHP file to test, and .codacy.json is a folder.
Also, /src belongs to root. 

```
-----
bin
dev
docs
etc
home
jre
lib
lib64
linuxrc
media
mnt
proc
root
run
sbin
src
sys
tmp
usr
var
-----
total 4
drwxr-xr-x    3 root     root          60 Mar 29 08:46 .
drwxr-xr-x   49 root     root        4.0K Mar 29 08:46 ..
drwxr-xr-x    2 root     root          40 Mar 29 08:46 .codacy.json
-----
more: read error: Is a directory
-----
total 0
drwxr-xr-x    2 root     root          40 Mar 29 08:46 .
drwxr-xr-x    3 root     root          60 Mar 29 08:46 ..

```

**Comment by rtfpessoa** [comment]
That is weird. Today I have a very complete day but as soon as I can I will try to test this.

But at least in my computer plugins was working and also on circle ci. Since the last update something changed that made it fail.

**Comment by dseguy** [comment]
Upgraded sbt to 1.1.2
Tested with the symbolic link with no better luck.
I'm reverting to only one build (not two, as currently). 

Tried to run the brakeman tests with Codacy-plugin-test : It also gets 'No results received!'.

I'm running on OSX 10.11.6

**Comment by dseguy** [comment]
Moved to anapsix/alpine-java base image. I found some incompatibilities between Alpine and jdk8 images while buidling the gremlin server. So, I tried another way to build everything at once, and alpine-java was perfect. 

The final image is 719Mb, with no optimization. Looks good. Performances are in line. 

Tests are still stuck at the same level : no results. 

CircleCI doesn't timeout anymore, and the results are the same as mine, except for the recurring failed destroy operation. 

I'd like to find a way to get better feedback from circleCI : I rely on the docker logs here, but I don't know what is the error on circleCI, nor how I can trace anything.

**Comment by rtfpessoa** [comment]
I am running thew tests in Mac OS 10.13.3  and in Ubuntu in circle ci they were working so should not be a OS problem.

Regarding feedback the best way to check circle ci is to trigger a build with SSH and go there and check the docker logs.

Later when I can run this locally again I might get some extra insights.

**Comment by dseguy** [comment]
The current version of exakat (1.2.0a) complains if .codacy.json is a directory, or when no meaningful information is found the .codacy.json (like, no files, or no entry for Exakat). When no .codacy.json file is to be found, it is not reported, as expected.

I do get that error ({"filename":".codacy.json","message":".codacy.json is a directory"}) when running the tests here. Although, I still get ' No results received! ' by the codacy-plugin-test. 

Hopefully, that will help resolving this situation.

**Comment by rtfpessoa** [comment]
Are you using Dockcer for Mac? Which version? I am using `17.12.0-ce-mac55 (23011)`

That error only happens if you have a folder on the docker in `docs/tests` named `.codacy.json`.

**Comment by dseguy** [comment]
I use `Docker version 17.05.0-ce, build 89658be`, so I'll upgrade. 

I have removed any .codacy.json from docs/tests and I pay attention to this now. This is still happening, though.

**Comment by dseguy** [comment]
Upgraded to `18.03.0-ce` and now, all the tests are passing locally. Good job, Rodrigo!

That doesn't help with CircleCI yet (the version I used is already pushed), but I'm now able to fix those pesky bug locally.

**Comment by dseguy** [comment]
It seems it ran again :) 👍 

What did you do ?!?

**Comment by rtfpessoa** [comment]
I just restarted the build to go in SSH. And it passed 😕

**Comment by dseguy** [comment]
So, at that point, what is the next step ? 

I presume you have more testing to run on your side. I have a few ideas I would like to try once a first version is validated.

**Comment by rtfpessoa** [comment]
I will pass this to product and they will prioritise the work. We have a couple more tools and we should begin them at the same time. Will let you know if we need anything.

**Review by rtfpessoa — APPROVED** [review]

**Pull request merged**
